print("Hello Python world!")
print("What's your name?")
name=input()
print("How old are you?")
age=input()
print("Hello "+name+", glad to meet you.")
print('It is wonderful that you beginning to study Python in your '+str(age)+' years old.')
print("You'll be "+str(int(age)+1)+" years old in one year.")
print('Good luck!')
